// Write a simple JavaScript program to join all elements of the following array into a string.
// Sample array : myColor = ["Red", "Green", "White", "Black"];
// Expected Output :
// "Red,Green,White,Black"
// "Red,Green,White,Black"
// "Red+Green+White+Black"
mycolor = ["red","green","white","black"];
console.log(mycolor.toString())
console.log(mycolor.join(","));
console.log(mycolor.join("+"));